[package]
name = "reo"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/objectionary/reo"
description = "Transpiler of EO programs to Rust functions"
readme = "README.md"
license-file = "LICENSE.txt"
homepage = "https://github.com/objectionary/reo"
keywords = ["eolang", "compiler", "oop"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.68"
regex = "1.7.0"
lazy_static = "1.4.0"
log = "0.4.17"
sxd-xpath = "0.4.2"
sxd-document = "0.3.2"
clap = { version = "4.0.14", features = ["cargo", "wrap_help"] }
simple_logger = "2.3.0"
xml-builder = "0.5.1"
ctor = "0.1.26"
itertools = "0.10.5"
glob = "0.3.0"
hex = "0.4.3"
bincode = "1.3.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
filetime = "0.2.19"

[dev-dependencies]
assert_cmd = "2.0.7"
fsutils = "0.1.7"
tempfile = "3.3.0"
predicates = "2.1.5"
rand = "0.8.5"
